spring:
  application:
    name: eventClean

  datasource:
    url: jdbc:postgresql://localhost:5432/eventClean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration